
CREATE TABLE tb_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL,
    data_pedido TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    valor_total NUMERIC(10, 2) NOT NULL,
    descricao VARCHAR(255)
);


CREATE TABLE tb_item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    pedido_id BIGINT
);


ALTER TABLE tb_item_pedido
ADD CONSTRAINT fk_item_pedido_on_pedido
FOREIGN KEY (pedido_id) REFERENCES tb_pedido(id);